Add windows requierement
gfx-rs/nv-flip-rs pull request #3
Opened 2023-09-20 23:55 UTC by Stargateur

look like MCVC 2019 is not enough for this project.

2023-09-21 02:09 UTC, cwfitzgerald requested changes
Interesting, what errors do you get on msvc? 

In addition to adding it to the Readme, we should explicitly check the msvc version in the build script (using https://docs.rs/cc/latest/cc/windows_registry/fn.find_vs_version.html) and raise an explicit error.

2023-09-21 02:09 UTC, cwfitzgerald commented on README.md
> +## Requirement
Let's just make a top level windows section.

2023-09-21 02:09 UTC, cwfitzgerald commented on README.md
> +- MCVC 2022
This needs a bit more prose.


```suggestion
The FLIP library requires MSVC 2022 or newer to compile. 
```

2023-09-21 06:58 UTC, Stargateur commented
I didn't save the error sorry, I think he didn't like `auto` from C23, but it seems MSVC 2022 is fine with it. https://github.com/gfx-rs/nv-flip-rs/blob/d532489e30e8d40859e8694933af5f7d07e0e03b/nv-flip-sys/src/bindings.cpp#L70

2023-09-21 07:41 UTC, Stargateur commented
here I uninstall it just for you haha:

```none
[nv-flip-sys 0.1.1] TARGET = Some("x86_64-pc-windows-msvc")
[nv-flip-sys 0.1.1] OPT_LEVEL = Some("0")
[nv-flip-sys 0.1.1] HOST = Some("x86_64-pc-windows-msvc")
[nv-flip-sys 0.1.1] cargo:rerun-if-env-changed=CXX_x86_64-pc-windows-msvc
[nv-flip-sys 0.1.1] CXX_x86_64-pc-windows-msvc = None
[nv-flip-sys 0.1.1] cargo:rerun-if-env-changed=CXX_x86_64_pc_windows_msvc
[nv-flip-sys 0.1.1] CXX_x86_64_pc_windows_msvc = None
[nv-flip-sys 0.1.1] cargo:rerun-if-env-changed=HOST_CXX
[nv-flip-sys 0.1.1] HOST_CXX = None
[nv-flip-sys 0.1.1] cargo:rerun-if-env-changed=CXX
[nv-flip-sys 0.1.1] CXX = None
[nv-flip-sys 0.1.1] cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
[nv-flip-sys 0.1.1] CRATE_CC_NO_DEFAULTS = None
[nv-flip-sys 0.1.1] CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
[nv-flip-sys 0.1.1] DEBUG = Some("true")
[nv-flip-sys 0.1.1] cargo:rerun-if-env-changed=CXXFLAGS_x86_64-pc-windows-msvc
[nv-flip-sys 0.1.1] CXXFLAGS_x86_64-pc-windows-msvc = None
[nv-flip-sys 0.1.1] cargo:rerun-if-env-changed=CXXFLAGS_x86_64_pc_windows_msvc
[nv-flip-sys 0.1.1] CXXFLAGS_x86_64_pc_windows_msvc = None
[nv-flip-sys 0.1.1] cargo:rerun-if-env-changed=HOST_CXXFLAGS
[nv-flip-sys 0.1.1] HOST_CXXFLAGS = None
[nv-flip-sys 0.1.1] cargo:rerun-if-env-changed=CXXFLAGS
[nv-flip-sys 0.1.1] CXXFLAGS = None
[nv-flip-sys 0.1.1] cargo:rerun-if-env-changed=CXX_x86_64-pc-windows-msvc
[nv-flip-sys 0.1.1] CXX_x86_64-pc-windows-msvc = None
[nv-flip-sys 0.1.1] cargo:rerun-if-env-changed=CXX_x86_64_pc_windows_msvc
[nv-flip-sys 0.1.1] CXX_x86_64_pc_windows_msvc = None
[nv-flip-sys 0.1.1] cargo:rerun-if-env-changed=HOST_CXX
[nv-flip-sys 0.1.1] HOST_CXX = None
[nv-flip-sys 0.1.1] cargo:rerun-if-env-changed=CXX
[nv-flip-sys 0.1.1] CXX = None
[nv-flip-sys 0.1.1] cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
[nv-flip-sys 0.1.1] CRATE_CC_NO_DEFAULTS = None
[nv-flip-sys 0.1.1] CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
[nv-flip-sys 0.1.1] cargo:rerun-if-env-changed=CXXFLAGS_x86_64-pc-windows-msvc
[nv-flip-sys 0.1.1] CXXFLAGS_x86_64-pc-windows-msvc = None
[nv-flip-sys 0.1.1] cargo:rerun-if-env-changed=CXXFLAGS_x86_64_pc_windows_msvc
[nv-flip-sys 0.1.1] CXXFLAGS_x86_64_pc_windows_msvc = None
[nv-flip-sys 0.1.1] cargo:rerun-if-env-changed=HOST_CXXFLAGS
[nv-flip-sys 0.1.1] HOST_CXXFLAGS = None
[nv-flip-sys 0.1.1] cargo:rerun-if-env-changed=CXXFLAGS
[nv-flip-sys 0.1.1] CXXFLAGS = None
[nv-flip-sys 0.1.1] cargo:rerun-if-env-changed=CXX_x86_64-pc-windows-msvc
[nv-flip-sys 0.1.1] CXX_x86_64-pc-windows-msvc = None
[nv-flip-sys 0.1.1] cargo:rerun-if-env-changed=CXX_x86_64_pc_windows_msvc
[nv-flip-sys 0.1.1] CXX_x86_64_pc_windows_msvc = None
[nv-flip-sys 0.1.1] cargo:rerun-if-env-changed=HOST_CXX
[nv-flip-sys 0.1.1] HOST_CXX = None
[nv-flip-sys 0.1.1] cargo:rerun-if-env-changed=CXX
[nv-flip-sys 0.1.1] CXX = None
[nv-flip-sys 0.1.1] cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
[nv-flip-sys 0.1.1] CRATE_CC_NO_DEFAULTS = None
[nv-flip-sys 0.1.1] CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
[nv-flip-sys 0.1.1] cargo:rerun-if-env-changed=CXXFLAGS_x86_64-pc-windows-msvc
[nv-flip-sys 0.1.1] CXXFLAGS_x86_64-pc-windows-msvc = None
[nv-flip-sys 0.1.1] cargo:rerun-if-env-changed=CXXFLAGS_x86_64_pc_windows_msvc
[nv-flip-sys 0.1.1] CXXFLAGS_x86_64_pc_windows_msvc = None
[nv-flip-sys 0.1.1] cargo:rerun-if-env-changed=HOST_CXXFLAGS
[nv-flip-sys 0.1.1] HOST_CXXFLAGS = None
[nv-flip-sys 0.1.1] cargo:rerun-if-env-changed=CXXFLAGS
[nv-flip-sys 0.1.1] CXXFLAGS = None
[nv-flip-sys 0.1.1] cargo:rerun-if-env-changed=CXX_x86_64-pc-windows-msvc
[nv-flip-sys 0.1.1] CXX_x86_64-pc-windows-msvc = None
[nv-flip-sys 0.1.1] cargo:rerun-if-env-changed=CXX_x86_64_pc_windows_msvc
[nv-flip-sys 0.1.1] CXX_x86_64_pc_windows_msvc = None
[nv-flip-sys 0.1.1] cargo:rerun-if-env-changed=HOST_CXX
[nv-flip-sys 0.1.1] HOST_CXX = None
[nv-flip-sys 0.1.1] cargo:rerun-if-env-changed=CXX
[nv-flip-sys 0.1.1] CXX = None
[nv-flip-sys 0.1.1] cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
[nv-flip-sys 0.1.1] CRATE_CC_NO_DEFAULTS = None
[nv-flip-sys 0.1.1] CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
[nv-flip-sys 0.1.1] cargo:rerun-if-env-changed=CXXFLAGS_x86_64-pc-windows-msvc
[nv-flip-sys 0.1.1] CXXFLAGS_x86_64-pc-windows-msvc = None
[nv-flip-sys 0.1.1] cargo:rerun-if-env-changed=CXXFLAGS_x86_64_pc_windows_msvc
[nv-flip-sys 0.1.1] CXXFLAGS_x86_64_pc_windows_msvc = None
[nv-flip-sys 0.1.1] cargo:rerun-if-env-changed=HOST_CXXFLAGS
[nv-flip-sys 0.1.1] HOST_CXXFLAGS = None
[nv-flip-sys 0.1.1] cargo:rerun-if-env-changed=CXXFLAGS
[nv-flip-sys 0.1.1] CXXFLAGS = None
[nv-flip-sys 0.1.1] running: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.22.27905\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-Z7" "-Brepro" "-I" "src/" "-I" "extern/cpp/common/" "-I" "extern/cpp/CPP/" "-W4" "/std:c++17" "/permissive-" "-DNOMINMAX" "-FoC:\\Users\\plask\\git\\nv-flip-rs\\target\\debug\\build\\nv-flip-sys-f86ae066846a23b3\\out\\src/bindings.o" "-c" "src/bindings.cpp"
[nv-flip-sys 0.1.1] bindings.cpp
[nv-flip-sys 0.1.1] C:\Users\plask\git\nv-flip-rs\nv-flip-sys\extern\cpp\common\../CPP/color.h(70): warning C4201: extension non standard utilis�e�: struct/union sans nom
[nv-flip-sys 0.1.1] C:\Users\plask\git\nv-flip-rs\nv-flip-sys\extern\cpp\common\../CPP/color.h(71): warning C4201: extension non standard utilis�e�: struct/union sans nom
[nv-flip-sys 0.1.1] C:\Users\plask\git\nv-flip-rs\nv-flip-sys\extern\cpp\common\../CPP/color.h(72): warning C4201: extension non standard utilis�e�: struct/union sans nom
[nv-flip-sys 0.1.1] C:\Users\plask\git\nv-flip-rs\nv-flip-sys\extern\cpp\common\../CPP/color.h(119): warning C4458: la d�claration de 'v' masque le membre de classe
[nv-flip-sys 0.1.1] C:\Users\plask\git\nv-flip-rs\nv-flip-sys\extern\cpp\common\../CPP/color.h(72): note: voir la d�claration de 'FLIP::color3::<unnamed-tag>::v'
[nv-flip-sys 0.1.1] C:\Users\plask\git\nv-flip-rs\nv-flip-sys\extern\cpp\common\../CPP/color.h(124): warning C4458: la d�claration de 'v' masque le membre de classe
[nv-flip-sys 0.1.1] C:\Users\plask\git\nv-flip-rs\nv-flip-sys\extern\cpp\common\../CPP/color.h(72): note: voir la d�claration de 'FLIP::color3::<unnamed-tag>::v'
[nv-flip-sys 0.1.1] C:\Users\plask\git\nv-flip-rs\nv-flip-sys\extern\cpp\common\../CPP/color.h(129): warning C4458: la d�claration de 'v' masque le membre de classe
[nv-flip-sys 0.1.1] C:\Users\plask\git\nv-flip-rs\nv-flip-sys\extern\cpp\common\../CPP/color.h(72): note: voir la d�claration de 'FLIP::color3::<unnamed-tag>::v'
[nv-flip-sys 0.1.1] C:\Users\plask\git\nv-flip-rs\nv-flip-sys\extern\cpp\common\../CPP/color.h(134): warning C4458: la d�claration de 'v' masque le membre de classe
[nv-flip-sys 0.1.1] C:\Users\plask\git\nv-flip-rs\nv-flip-sys\extern\cpp\common\../CPP/color.h(72): note: voir la d�claration de 'FLIP::color3::<unnamed-tag>::v'
[nv-flip-sys 0.1.1] C:\Users\plask\git\nv-flip-rs\nv-flip-sys\extern\cpp\common\../CPP/color.h(139): warning C4458: la d�claration de 'v' masque le membre de classe
[nv-flip-sys 0.1.1] C:\Users\plask\git\nv-flip-rs\nv-flip-sys\extern\cpp\common\../CPP/color.h(72): note: voir la d�claration de 'FLIP::color3::<unnamed-tag>::v'
[nv-flip-sys 0.1.1] C:\Users\plask\git\nv-flip-rs\nv-flip-sys\extern\cpp\common\../CPP/color.h(144): warning C4458: la d�claration de 'v' masque le membre de classe
[nv-flip-sys 0.1.1] C:\Users\plask\git\nv-flip-rs\nv-flip-sys\extern\cpp\common\../CPP/color.h(72): note: voir la d�claration de 'FLIP::color3::<unnamed-tag>::v'
[nv-flip-sys 0.1.1] C:\Users\plask\git\nv-flip-rs\nv-flip-sys\extern\cpp\common\../CPP/color.h(149): warning C4458: la d�claration de 'v' masque le membre de classe
[nv-flip-sys 0.1.1] C:\Users\plask\git\nv-flip-rs\nv-flip-sys\extern\cpp\common\../CPP/color.h(72): note: voir la d�claration de 'FLIP::color3::<unnamed-tag>::v'
[nv-flip-sys 0.1.1] C:\Users\plask\git\nv-flip-rs\nv-flip-sys\extern\cpp\common\../CPP/color.h(154): warning C4458: la d�claration de 'v' masque l [...]

2023-09-21 07:53 UTC, Stargateur commented
It's look like MSVC 2019 16.11.30 is enough to compile nv-flip-sys

2023-09-21 14:00 UTC, cwfitzgerald commented
Cool, thank you!

2023-09-21 22:49 UTC, cwfitzgerald commented
(This still needs a proper error in the build script)

2026-03-10 03:48 UTC, cwfitzgerald commented
I'm closing this as stale, please re-submit if you're interested in following this through

2026-03-10 03:48 UTC, closed without merging